# See [config.py] for documentation on this!

[okr]
database_url = "sqlite+aiosqlite:///db.sqlite"

[okr.admin]
username = "admin"
email = "admin@okr.local"
password_hash = ""

[okr.jwt_config]
secret = "SECRET"
validity_duration_hours = 24
